export const data = {
  data: {
    columns: {
      wdir: {
        id: "wdir",
        name: "Wind Direction",
        type: 2,
        unit: null,
      },
      uvindex: {
        id: "uvindex",
        name: "weather_uvindex",
        type: 2,
        unit: null,
      },
      latitude: {
        id: "latitude",
        name: "Latitude",
        type: 2,
        unit: null,
      },
      preciptype: {
        id: "preciptype",
        name: "weather_preciptype",
        type: 1,
        unit: null,
      },
      cin: {
        id: "cin",
        name: "weather_cin",
        type: 2,
        unit: null,
      },
      cloudcover: {
        id: "cloudcover",
        name: "Cloud Cover",
        type: 2,
        unit: null,
      },
      pop: {
        id: "pop",
        name: "Chance Precipitation (%)",
        type: 2,
        unit: null,
      },
      mint: {
        id: "mint",
        name: "Minimum Temperature",
        type: 2,
        unit: "degF",
      },
      datetime: {
        id: "datetime",
        name: "Date time",
        type: 3,
        unit: null,
      },
      precip: {
        id: "precip",
        name: "Precipitation",
        type: 2,
        unit: "in",
      },
      solarradiation: {
        id: "solarradiation",
        name: "Solar Radiation",
        type: 2,
        unit: null,
      },
      dew: {
        id: "dew",
        name: "Dew Point",
        type: 2,
        unit: "degf",
      },
      humidity: {
        id: "humidity",
        name: "Relative Humidity",
        type: 2,
        unit: null,
      },
      longitude: {
        id: "longitude",
        name: "Longitude",
        type: 2,
        unit: null,
      },
      temp: {
        id: "temp",
        name: "Temperature",
        type: 2,
        unit: "degf",
      },
      address: {
        id: "address",
        name: "Address",
        type: 1,
        unit: null,
      },
      maxt: {
        id: "maxt",
        name: "Maximum Temperature",
        type: 2,
        unit: "degF",
      },
      visibility: {
        id: "visibility",
        name: "Visibility",
        type: 2,
        unit: "mi",
      },
      wspd: {
        id: "wspd",
        name: "Wind Speed",
        type: 2,
        unit: "mph",
      },
      severerisk: {
        id: "severerisk",
        name: "weather_severerisk",
        type: 2,
        unit: null,
      },
      solarenergy: {
        id: "solarenergy",
        name: "Solar Energy",
        type: 2,
        unit: null,
      },
      resolvedAddress: {
        id: "resolvedAddress",
        name: "Resolved Address",
        type: 1,
        unit: null,
      },
      heatindex: {
        id: "heatindex",
        name: "Heat Index",
        type: 2,
        unit: "degf",
      },
      snowdepth: {
        id: "snowdepth",
        name: "Snow Depth",
        type: 2,
        unit: "in",
      },
      sealevelpressure: {
        id: "sealevelpressure",
        name: "Sea Level Pressure",
        type: 2,
        unit: "mb",
      },
      snow: {
        id: "snow",
        name: "Snow",
        type: 2,
        unit: "in",
      },
      name: {
        id: "name",
        name: "Name",
        type: 1,
        unit: null,
      },
      wgust: {
        id: "wgust",
        name: "Wind Gust",
        type: 2,
        unit: "mph",
      },
      conditions: {
        id: "conditions",
        name: "Conditions",
        type: 1,
        unit: null,
      },
      windchill: {
        id: "windchill",
        name: "Wind Chill",
        type: 2,
        unit: "degf",
      },
      cape: {
        id: "cape",
        name: "weather_cape",
        type: 2,
        unit: null,
      },
    },
    remainingCost: 0,
    queryCost: 1,
    messages: null,
    locations: {
      "6.0329, 80.2168": {
        stationContributions: null,
        values: [
          {
            wdir: 243.5,
            uvindex: 2.1,
            datetimeStr: "2024-04-14T00:30:00+05:30",
            preciptype: "",
            cin: -10.5,
            cloudcover: 98.3,
            pop: 100,
            mint: 81.4,
            datetime: 1713054600000,
            precip: 0.28,
            solarradiation: 202.6,
            dew: 74.2,
            humidity: 76.2,
            temp: 82.5,
            maxt: 84.1,
            visibility: 4.5,
            wspd: 2.3,
            severerisk: 13.6,
            solarenergy: 0.7,
            heatindex: 91.6,
            snowdepth: 0,
            sealevelpressure: 1009.5,
            snow: 0,
            wgust: 8.5,
            conditions: "Rain, Overcast",
            windchill: null,
            cape: 556.7,
          },
          {
            wdir: 216,
            uvindex: 2.3,
            datetimeStr: "2024-04-15T00:30:00+05:30",
            preciptype: "",
            cin: -15.9,
            cloudcover: 95,
            pop: 100,
            mint: 79.4,
            datetime: 1713141000000,
            precip: 0.51,
            solarradiation: 230.7,
            dew: 74.6,
            humidity: 78.9,
            temp: 81.9,
            maxt: 86.8,
            visibility: 2.5,
            wspd: 4.1,
            severerisk: 13.3,
            solarenergy: 0.8,
            heatindex: 95,
            snowdepth: 0,
            sealevelpressure: 1010.1,
            snow: 0,
            wgust: 8.7,
            conditions: "Rain, Overcast",
            windchill: null,
            cape: 661.3,
          },
          {
            wdir: 106.4,
            uvindex: 2.2,
            datetimeStr: "2024-04-16T00:30:00+05:30",
            preciptype: "",
            cin: -15.2,
            cloudcover: 94.8,
            pop: 96.8,
            mint: 78.5,
            datetime: 1713227400000,
            precip: 0.18,
            solarradiation: 227.9,
            dew: 74.4,
            humidity: 78.1,
            temp: 82.1,
            maxt: 87,
            visibility: 8.5,
            wspd: 4.4,
            severerisk: 15.8,
            solarenergy: 0.8,
            heatindex: 95.6,
            snowdepth: 0,
            sealevelpressure: 1010,
            snow: 0,
            wgust: 9.2,
            conditions: "Rain, Overcast",
            windchill: null,
            cape: 778.9,
          },
          {
            wdir: 197.4,
            uvindex: 2.8,
            datetimeStr: "2024-04-17T00:30:00+05:30",
            preciptype: "",
            cin: -6.7,
            cloudcover: 95.9,
            pop: 54.8,
            mint: 79.8,
            datetime: 1713313800000,
            precip: 0.03,
            solarradiation: 276.8,
            dew: 74.4,
            humidity: 75.1,
            temp: 83.2,
            maxt: 85.9,
            visibility: 12.3,
            wspd: 5.6,
            severerisk: 23.3,
            solarenergy: 1,
            heatindex: 94.1,
            snowdepth: 0,
            sealevelpressure: 1010,
            snow: 0,
            wgust: 10.7,
            conditions: "Rain, Overcast",
            windchill: null,
            cape: 1005.3,
          },
          {
            wdir: 279.1,
            uvindex: 2.8,
            datetimeStr: "2024-04-18T00:30:00+05:30",
            preciptype: "",
            cin: -0.5,
            cloudcover: 87.1,
            pop: 71,
            mint: 81.4,
            datetime: 1713400200000,
            precip: 0.07,
            solarradiation: 275.4,
            dew: 75.8,
            humidity: 76.6,
            temp: 84,
            maxt: 86.8,
            visibility: 12.6,
            wspd: 9.5,
            severerisk: 38.8,
            solarenergy: 1,
            heatindex: 96.5,
            snowdepth: 0,
            sealevelpressure: 1009.5,
            snow: 0,
            wgust: 14.8,
            conditions: "Rain, Overcast",
            windchill: null,
            cape: 1625,
          },
          {
            wdir: 275,
            uvindex: 2.8,
            datetimeStr: "2024-04-19T00:30:00+05:30",
            preciptype: "",
            cin: -0.9,
            cloudcover: 70.3,
            pop: 83.9,
            mint: 81.1,
            datetime: 1713486600000,
            precip: 0.13,
            solarradiation: 287.9,
            dew: 76.4,
            humidity: 78.1,
            temp: 84,
            maxt: 86.6,
            visibility: 13.2,
            wspd: 10.4,
            severerisk: 51.3,
            solarenergy: 1,
            heatindex: 97.2,
            snowdepth: 0,
            sealevelpressure: 1008.7,
            snow: 0,
            wgust: 15,
            conditions: "Rain, Partially cloudy",
            windchill: null,
            cape: 1937.4,
          },
          {
            wdir: 263.8,
            uvindex: 3,
            datetimeStr: "2024-04-20T00:30:00+05:30",
            preciptype: "",
            cin: -0.5,
            cloudcover: 36.9,
            pop: 71,
            mint: 81.2,
            datetime: 1713573000000,
            precip: 0.16,
            solarradiation: 298,
            dew: 76.4,
            humidity: 78.4,
            temp: 83.9,
            maxt: 86.3,
            visibility: 10.5,
            wspd: 9.8,
            severerisk: 55,
            solarenergy: 1.1,
            heatindex: 96.2,
            snowdepth: 0,
            sealevelpressure: 1008.4,
            snow: 0,
            wgust: 15.4,
            conditions: "Rain, Partially cloudy",
            windchill: null,
            cape: 1949.2,
          },
          {
            wdir: 249.8,
            uvindex: 3,
            datetimeStr: "2024-04-21T00:30:00+05:30",
            preciptype: "",
            cin: -0.2,
            cloudcover: 32.6,
            pop: 74.2,
            mint: 81.6,
            datetime: 1713659400000,
            precip: 0.11,
            solarradiation: 298.3,
            dew: 76.1,
            humidity: 78,
            temp: 83.7,
            maxt: 85.9,
            visibility: 12.4,
            wspd: 7.6,
            severerisk: 43.8,
            solarenergy: 1.1,
            heatindex: 95.5,
            snowdepth: 0,
            sealevelpressure: 1008.5,
            snow: 0,
            wgust: 12.2,
            conditions: "Rain, Partially cloudy",
            windchill: null,
            cape: 1747.3,
          },
          {
            wdir: 251.5,
            uvindex: 3,
            datetimeStr: "2024-04-22T00:30:00+05:30",
            preciptype: "",
            cin: -3.1,
            cloudcover: 48.9,
            pop: 67.7,
            mint: 81.9,
            datetime: 1713745800000,
            precip: 0.06,
            solarradiation: 297.6,
            dew: 75.7,
            humidity: 75.3,
            temp: 84.5,
            maxt: 87.3,
            visibility: 14.9,
            wspd: 7,
            severerisk: 50,
            solarenergy: 1.1,
            heatindex: 96.1,
            snowdepth: 0,
            sealevelpressure: 1007.9,
            snow: 0,
            wgust: 11.2,
            conditions: "Rain, Partially cloudy",
            windchill: null,
            cape: 1744.3,
          },
          {
            wdir: 241,
            uvindex: 2.6,
            datetimeStr: "2024-04-23T00:30:00+05:30",
            preciptype: "",
            cin: -1.2,
            cloudcover: 99.9,
            pop: 61.3,
            mint: 81.6,
            datetime: 1713832200000,
            precip: 0.13,
            solarradiation: 260.8,
            dew: 75.4,
            humidity: 76,
            temp: 83.8,
            maxt: 86.3,
            visibility: 8.5,
            wspd: 6.2,
            severerisk: 32.5,
            solarenergy: 0.9,
            heatindex: 94.8,
            snowdepth: 0,
            sealevelpressure: 1008,
            snow: 0,
            wgust: 9.6,
            conditions: "Rain, Overcast",
            windchill: null,
            cape: 1556.6,
          },
          {
            wdir: 184.8,
            uvindex: 2.8,
            datetimeStr: "2024-04-24T00:30:00+05:30",
            preciptype: "",
            cin: -2.3,
            cloudcover: 94.9,
            pop: 67.7,
            mint: 81.9,
            datetime: 1713918600000,
            precip: 0.02,
            solarradiation: 277.1,
            dew: 75.4,
            humidity: 75.2,
            temp: 84.1,
            maxt: 86.6,
            visibility: 15,
            wspd: 5.1,
            severerisk: 43.8,
            solarenergy: 1,
            heatindex: 96.1,
            snowdepth: 0,
            sealevelpressure: 1008.1,
            snow: 0,
            wgust: 8.9,
            conditions: "Rain, Overcast",
            windchill: null,
            cape: 1645.4,
          },
          {
            wdir: 164.7,
            uvindex: 3,
            datetimeStr: "2024-04-25T00:30:00+05:30",
            preciptype: "",
            cin: -2.5,
            cloudcover: 27,
            pop: 32.3,
            mint: 81.2,
            datetime: 1714005000000,
            precip: 0,
            solarradiation: 294.1,
            dew: 74.8,
            humidity: 74.5,
            temp: 83.8,
            maxt: 86.6,
            visibility: 15,
            wspd: 6.2,
            severerisk: 30,
            solarenergy: 1.1,
            heatindex: 95.3,
            snowdepth: 0,
            sealevelpressure: 1009.3,
            snow: 0,
            wgust: 9.6,
            conditions: "Partially cloudy",
            windchill: null,
            cape: 1285.8,
          },
          {
            wdir: 131.7,
            uvindex: 2.5,
            datetimeStr: "2024-04-26T00:30:00+05:30",
            preciptype: "",
            cin: -14,
            cloudcover: 23.2,
            pop: 35.5,
            mint: 80.1,
            datetime: 1714091400000,
            precip: 0,
            solarradiation: 262.1,
            dew: 75,
            humidity: 76.9,
            temp: 83.1,
            maxt: 86.3,
            visibility: 15,
            wspd: 6.5,
            severerisk: 34.2,
            solarenergy: 0.9,
            heatindex: 95.9,
            snowdepth: 0,
            sealevelpressure: 1008.5,
            snow: 0,
            wgust: 11.9,
            conditions: "Clear",
            windchill: null,
            cape: 1325.9,
          },
          {
            wdir: 127.6,
            uvindex: 3,
            datetimeStr: "2024-04-27T00:30:00+05:30",
            preciptype: "",
            cin: -11,
            cloudcover: 45.6,
            pop: 29,
            mint: 79.4,
            datetime: 1714177800000,
            precip: 0.03,
            solarradiation: 302,
            dew: 75.7,
            humidity: 78.2,
            temp: 83.3,
            maxt: 87.2,
            visibility: 15,
            wspd: 9.3,
            severerisk: 40,
            solarenergy: 1.1,
            heatindex: 96.2,
            snowdepth: 0,
            sealevelpressure: 1008,
            snow: 0,
            wgust: 15.4,
            conditions: "Partially cloudy",
            windchill: null,
            cape: 1590.4,
          },
          {
            wdir: 149.3,
            uvindex: 3,
            datetimeStr: "2024-04-28T00:30:00+05:30",
            preciptype: "",
            cin: -5.6,
            cloudcover: 15.9,
            pop: 32.3,
            mint: 79.2,
            datetime: 1714264200000,
            precip: 0.01,
            solarradiation: 289.9,
            dew: 75.8,
            humidity: 78.9,
            temp: 83.1,
            maxt: 86.4,
            visibility: 15,
            wspd: 7,
            severerisk: 43.8,
            solarenergy: 1,
            heatindex: 96.3,
            snowdepth: 0,
            sealevelpressure: 1008.3,
            snow: 0,
            wgust: 10.7,
            conditions: "Clear",
            windchill: null,
            cape: 1661.2,
          },
          {
            wdir: 224.2,
            uvindex: 2.8,
            datetimeStr: "2024-04-29T00:30:00+05:30",
            preciptype: "",
            cin: -1.5,
            cloudcover: 60.9,
            pop: 32.3,
            mint: 81.1,
            datetime: 1714350600000,
            precip: 0.05,
            solarradiation: 280,
            dew: 75.2,
            humidity: 76.5,
            temp: 83.5,
            maxt: 85.2,
            visibility: 15,
            wspd: 5.7,
            severerisk: 30,
            solarenergy: 1,
            heatindex: 93.7,
            snowdepth: 0,
            sealevelpressure: 1009.2,
            snow: 0,
            wgust: 9.8,
            conditions: "Partially cloudy",
            windchill: null,
            cape: 1543.4,
          },
        ],
        id: "6.0329, 80.2168",
        address: "6.0329, 80.2168",
        name: "6.0329, 80.2168",
        index: 0,
        latitude: 6.0329,
        longitude: 80.2168,
        distance: 0,
        time: 0,
        tz: "Asia/Colombo",
        currentConditions: {
          wdir: 150,
          temp: 89.5,
          sunrise: "2024-04-14T06:01:55+05:30",
          visibility: 12.4,
          wspd: 9.2,
          icon: "cloudy",
          stations: "",
          heatindex: 110.8,
          cloudcover: 88,
          datetime: "2024-04-14T11:30:00+05:30",
          precip: null,
          moonphase: 0.18,
          snowdepth: null,
          sealevelpressure: 1011,
          dew: 82.1,
          sunset: "2024-04-14T18:16:55+05:30",
          humidity: 79,
          wgust: null,
          windchill: null,
        },
        alerts: null,
      },
    },
  },
};
